# Maximum number of allowed redirects.
max_redirects = 20

# Proceed for server connections considered insecure (invalid TLS).
insecure = true

# Remap URI matching pattern to different URI.
remap = ['%7B%7BVersion%7D%7D 1.23.1', '%7B%7B%3C%20docsurl%20%3E%7D%7D https://sumo.dlr.de/docs']

# mkdocs generates sitemaps and rss but the links should have been checked elsewhere
exclude_path = ['\.xml$']

# Exclude URLs and mail addresses from checking (supports regex).
exclude = ['%7B%7BSource%7D%7D', '/sumo/images/logos/sumo-logo-white\.svg', 'github\.com', 'instagram\.com', 'linkedin\.com', 'researchgate\.net', 'scholar\.google\.de', 'twitter\.com', 'vector\.com', 'http://localhost:', 'https://www.bgu.tum.de/en/vt/home/', 'https://sumo-dlr-de\.translate\.goog/']
