name: linkcheck

on:
  workflow_dispatch:
  push:
    branches:
    - main
  schedule:
  - cron: '30 1 * * *' # daily at 01:30 UTC

jobs:
  external-link-check:
    runs-on: ubuntu-latest

    steps:
    - name: Cloning repository
      uses: actions/checkout@v4

    - name: Lychee Link Checker
      uses: lycheeverse/lychee-action@v1
      with:
        fail: true
        args: -c lychee.toml -n 20* index.html about/ conference/ contact/
